# Generated by Django 5.2.1 on 2025-06-12 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Arriendo_Peliculas.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('peliculas_alquiladas', models.ManyToManyField(blank=True, to='App_Arriendo_Peliculas.pelicula')),
            ],
        ),
    ]
