# Generated by Django 5.2.1 on 2025-06-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Arriendo_Peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='peliculas_alquiladas',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genero',
        ),
    ]
